"""empty message

Revision ID: ce6715011604
Revises: 30bfd066eb5a
Create Date: 2021-08-04 05:24:23.312203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce6715011604'
down_revision = '30bfd066eb5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_leagues')
    op.add_column('comments', sa.Column('index', sa.Integer(), nullable=True))
    op.drop_constraint('leagues_commissioner_fkey', 'leagues', type_='foreignkey')
    op.add_column('posts', sa.Column('leagueId', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('index', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'leagues', ['leagueId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'index')
    op.drop_column('posts', 'leagueId')
    op.create_foreign_key('leagues_commissioner_fkey', 'leagues', 'users', ['commissioner'], ['id'])
    op.drop_column('comments', 'index')
    op.create_table('users_leagues',
    sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('leagueId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['leagueId'], ['leagues.id'], name='users_leagues_leagueId_fkey'),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], name='users_leagues_userId_fkey'),
    sa.PrimaryKeyConstraint('userId', 'leagueId', name='users_leagues_pkey')
    )
    # ### end Alembic commands ###
